// File generated from our OpenAPI spec by Stainless.

package dev.arcade.models.admin.authproviders

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import dev.arcade.core.JsonValue
import dev.arcade.core.jsonMapper
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class AuthProviderCreateRequestTest {

    @Test
    fun create() {
        val authProviderCreateRequest =
            AuthProviderCreateRequest.builder()
                .id("id")
                .description("description")
                .externalId("external_id")
                .oauth2(
                    AuthProviderCreateRequest.Oauth2.builder()
                        .clientId("client_id")
                        .authorizeRequest(
                            AuthProviderCreateRequest.Oauth2.AuthorizeRequest.builder()
                                .endpoint("endpoint")
                                .authHeaderValueFormat("auth_header_value_format")
                                .authMethod("auth_method")
                                .method("method")
                                .params(
                                    AuthProviderCreateRequest.Oauth2.AuthorizeRequest.Params
                                        .builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .requestContentType(
                                    AuthProviderCreateRequest.Oauth2.AuthorizeRequest
                                        .RequestContentType
                                        .APPLICATION_X_WWW_FORM_URLENCODED
                                )
                                .responseContentType(
                                    AuthProviderCreateRequest.Oauth2.AuthorizeRequest
                                        .ResponseContentType
                                        .APPLICATION_X_WWW_FORM_URLENCODED
                                )
                                .responseMap(
                                    AuthProviderCreateRequest.Oauth2.AuthorizeRequest.ResponseMap
                                        .builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .build()
                        )
                        .clientSecret("client_secret")
                        .pkce(
                            AuthProviderCreateRequest.Oauth2.Pkce.builder()
                                .codeChallengeMethod("code_challenge_method")
                                .enabled(true)
                                .build()
                        )
                        .refreshRequest(
                            AuthProviderCreateRequest.Oauth2.RefreshRequest.builder()
                                .endpoint("endpoint")
                                .authHeaderValueFormat("auth_header_value_format")
                                .authMethod("auth_method")
                                .method("method")
                                .params(
                                    AuthProviderCreateRequest.Oauth2.RefreshRequest.Params.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .requestContentType(
                                    AuthProviderCreateRequest.Oauth2.RefreshRequest
                                        .RequestContentType
                                        .APPLICATION_X_WWW_FORM_URLENCODED
                                )
                                .responseContentType(
                                    AuthProviderCreateRequest.Oauth2.RefreshRequest
                                        .ResponseContentType
                                        .APPLICATION_X_WWW_FORM_URLENCODED
                                )
                                .responseMap(
                                    AuthProviderCreateRequest.Oauth2.RefreshRequest.ResponseMap
                                        .builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .build()
                        )
                        .scopeDelimiter(AuthProviderCreateRequest.Oauth2.ScopeDelimiter.Unknown0)
                        .tokenIntrospectionRequest(
                            AuthProviderCreateRequest.Oauth2.TokenIntrospectionRequest.builder()
                                .endpoint("endpoint")
                                .triggers(
                                    AuthProviderCreateRequest.Oauth2.TokenIntrospectionRequest
                                        .Triggers
                                        .builder()
                                        .onTokenGrant(true)
                                        .onTokenRefresh(true)
                                        .build()
                                )
                                .authHeaderValueFormat("auth_header_value_format")
                                .authMethod("auth_method")
                                .method("method")
                                .params(
                                    AuthProviderCreateRequest.Oauth2.TokenIntrospectionRequest
                                        .Params
                                        .builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .requestContentType(
                                    AuthProviderCreateRequest.Oauth2.TokenIntrospectionRequest
                                        .RequestContentType
                                        .APPLICATION_X_WWW_FORM_URLENCODED
                                )
                                .responseContentType(
                                    AuthProviderCreateRequest.Oauth2.TokenIntrospectionRequest
                                        .ResponseContentType
                                        .APPLICATION_X_WWW_FORM_URLENCODED
                                )
                                .responseMap(
                                    AuthProviderCreateRequest.Oauth2.TokenIntrospectionRequest
                                        .ResponseMap
                                        .builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .build()
                        )
                        .tokenRequest(
                            AuthProviderCreateRequest.Oauth2.TokenRequest.builder()
                                .endpoint("endpoint")
                                .authHeaderValueFormat("auth_header_value_format")
                                .authMethod("auth_method")
                                .method("method")
                                .params(
                                    AuthProviderCreateRequest.Oauth2.TokenRequest.Params.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .requestContentType(
                                    AuthProviderCreateRequest.Oauth2.TokenRequest.RequestContentType
                                        .APPLICATION_X_WWW_FORM_URLENCODED
                                )
                                .responseContentType(
                                    AuthProviderCreateRequest.Oauth2.TokenRequest
                                        .ResponseContentType
                                        .APPLICATION_X_WWW_FORM_URLENCODED
                                )
                                .responseMap(
                                    AuthProviderCreateRequest.Oauth2.TokenRequest.ResponseMap
                                        .builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .build()
                        )
                        .userInfoRequest(
                            AuthProviderCreateRequest.Oauth2.UserInfoRequest.builder()
                                .endpoint("endpoint")
                                .triggers(
                                    AuthProviderCreateRequest.Oauth2.UserInfoRequest.Triggers
                                        .builder()
                                        .onTokenGrant(true)
                                        .onTokenRefresh(true)
                                        .build()
                                )
                                .authHeaderValueFormat("auth_header_value_format")
                                .authMethod("auth_method")
                                .method("method")
                                .params(
                                    AuthProviderCreateRequest.Oauth2.UserInfoRequest.Params
                                        .builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .requestContentType(
                                    AuthProviderCreateRequest.Oauth2.UserInfoRequest
                                        .RequestContentType
                                        .APPLICATION_X_WWW_FORM_URLENCODED
                                )
                                .responseContentType(
                                    AuthProviderCreateRequest.Oauth2.UserInfoRequest
                                        .ResponseContentType
                                        .APPLICATION_X_WWW_FORM_URLENCODED
                                )
                                .responseMap(
                                    AuthProviderCreateRequest.Oauth2.UserInfoRequest.ResponseMap
                                        .builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .providerId("provider_id")
                .status("status")
                .type("type")
                .build()

        assertThat(authProviderCreateRequest.id()).isEqualTo("id")
        assertThat(authProviderCreateRequest.description()).contains("description")
        assertThat(authProviderCreateRequest.externalId()).contains("external_id")
        assertThat(authProviderCreateRequest.oauth2())
            .contains(
                AuthProviderCreateRequest.Oauth2.builder()
                    .clientId("client_id")
                    .authorizeRequest(
                        AuthProviderCreateRequest.Oauth2.AuthorizeRequest.builder()
                            .endpoint("endpoint")
                            .authHeaderValueFormat("auth_header_value_format")
                            .authMethod("auth_method")
                            .method("method")
                            .params(
                                AuthProviderCreateRequest.Oauth2.AuthorizeRequest.Params.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .requestContentType(
                                AuthProviderCreateRequest.Oauth2.AuthorizeRequest.RequestContentType
                                    .APPLICATION_X_WWW_FORM_URLENCODED
                            )
                            .responseContentType(
                                AuthProviderCreateRequest.Oauth2.AuthorizeRequest
                                    .ResponseContentType
                                    .APPLICATION_X_WWW_FORM_URLENCODED
                            )
                            .responseMap(
                                AuthProviderCreateRequest.Oauth2.AuthorizeRequest.ResponseMap
                                    .builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .build()
                    )
                    .clientSecret("client_secret")
                    .pkce(
                        AuthProviderCreateRequest.Oauth2.Pkce.builder()
                            .codeChallengeMethod("code_challenge_method")
                            .enabled(true)
                            .build()
                    )
                    .refreshRequest(
                        AuthProviderCreateRequest.Oauth2.RefreshRequest.builder()
                            .endpoint("endpoint")
                            .authHeaderValueFormat("auth_header_value_format")
                            .authMethod("auth_method")
                            .method("method")
                            .params(
                                AuthProviderCreateRequest.Oauth2.RefreshRequest.Params.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .requestContentType(
                                AuthProviderCreateRequest.Oauth2.RefreshRequest.RequestContentType
                                    .APPLICATION_X_WWW_FORM_URLENCODED
                            )
                            .responseContentType(
                                AuthProviderCreateRequest.Oauth2.RefreshRequest.ResponseContentType
                                    .APPLICATION_X_WWW_FORM_URLENCODED
                            )
                            .responseMap(
                                AuthProviderCreateRequest.Oauth2.RefreshRequest.ResponseMap
                                    .builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .build()
                    )
                    .scopeDelimiter(AuthProviderCreateRequest.Oauth2.ScopeDelimiter.Unknown0)
                    .tokenIntrospectionRequest(
                        AuthProviderCreateRequest.Oauth2.TokenIntrospectionRequest.builder()
                            .endpoint("endpoint")
                            .triggers(
                                AuthProviderCreateRequest.Oauth2.TokenIntrospectionRequest.Triggers
                                    .builder()
                                    .onTokenGrant(true)
                                    .onTokenRefresh(true)
                                    .build()
                            )
                            .authHeaderValueFormat("auth_header_value_format")
                            .authMethod("auth_method")
                            .method("method")
                            .params(
                                AuthProviderCreateRequest.Oauth2.TokenIntrospectionRequest.Params
                                    .builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .requestContentType(
                                AuthProviderCreateRequest.Oauth2.TokenIntrospectionRequest
                                    .RequestContentType
                                    .APPLICATION_X_WWW_FORM_URLENCODED
                            )
                            .responseContentType(
                                AuthProviderCreateRequest.Oauth2.TokenIntrospectionRequest
                                    .ResponseContentType
                                    .APPLICATION_X_WWW_FORM_URLENCODED
                            )
                            .responseMap(
                                AuthProviderCreateRequest.Oauth2.TokenIntrospectionRequest
                                    .ResponseMap
                                    .builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .build()
                    )
                    .tokenRequest(
                        AuthProviderCreateRequest.Oauth2.TokenRequest.builder()
                            .endpoint("endpoint")
                            .authHeaderValueFormat("auth_header_value_format")
                            .authMethod("auth_method")
                            .method("method")
                            .params(
                                AuthProviderCreateRequest.Oauth2.TokenRequest.Params.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .requestContentType(
                                AuthProviderCreateRequest.Oauth2.TokenRequest.RequestContentType
                                    .APPLICATION_X_WWW_FORM_URLENCODED
                            )
                            .responseContentType(
                                AuthProviderCreateRequest.Oauth2.TokenRequest.ResponseContentType
                                    .APPLICATION_X_WWW_FORM_URLENCODED
                            )
                            .responseMap(
                                AuthProviderCreateRequest.Oauth2.TokenRequest.ResponseMap.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .build()
                    )
                    .userInfoRequest(
                        AuthProviderCreateRequest.Oauth2.UserInfoRequest.builder()
                            .endpoint("endpoint")
                            .triggers(
                                AuthProviderCreateRequest.Oauth2.UserInfoRequest.Triggers.builder()
                                    .onTokenGrant(true)
                                    .onTokenRefresh(true)
                                    .build()
                            )
                            .authHeaderValueFormat("auth_header_value_format")
                            .authMethod("auth_method")
                            .method("method")
                            .params(
                                AuthProviderCreateRequest.Oauth2.UserInfoRequest.Params.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .requestContentType(
                                AuthProviderCreateRequest.Oauth2.UserInfoRequest.RequestContentType
                                    .APPLICATION_X_WWW_FORM_URLENCODED
                            )
                            .responseContentType(
                                AuthProviderCreateRequest.Oauth2.UserInfoRequest.ResponseContentType
                                    .APPLICATION_X_WWW_FORM_URLENCODED
                            )
                            .responseMap(
                                AuthProviderCreateRequest.Oauth2.UserInfoRequest.ResponseMap
                                    .builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(authProviderCreateRequest.providerId()).contains("provider_id")
        assertThat(authProviderCreateRequest.status()).contains("status")
        assertThat(authProviderCreateRequest.type()).contains("type")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val authProviderCreateRequest =
            AuthProviderCreateRequest.builder()
                .id("id")
                .description("description")
                .externalId("external_id")
                .oauth2(
                    AuthProviderCreateRequest.Oauth2.builder()
                        .clientId("client_id")
                        .authorizeRequest(
                            AuthProviderCreateRequest.Oauth2.AuthorizeRequest.builder()
                                .endpoint("endpoint")
                                .authHeaderValueFormat("auth_header_value_format")
                                .authMethod("auth_method")
                                .method("method")
                                .params(
                                    AuthProviderCreateRequest.Oauth2.AuthorizeRequest.Params
                                        .builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .requestContentType(
                                    AuthProviderCreateRequest.Oauth2.AuthorizeRequest
                                        .RequestContentType
                                        .APPLICATION_X_WWW_FORM_URLENCODED
                                )
                                .responseContentType(
                                    AuthProviderCreateRequest.Oauth2.AuthorizeRequest
                                        .ResponseContentType
                                        .APPLICATION_X_WWW_FORM_URLENCODED
                                )
                                .responseMap(
                                    AuthProviderCreateRequest.Oauth2.AuthorizeRequest.ResponseMap
                                        .builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .build()
                        )
                        .clientSecret("client_secret")
                        .pkce(
                            AuthProviderCreateRequest.Oauth2.Pkce.builder()
                                .codeChallengeMethod("code_challenge_method")
                                .enabled(true)
                                .build()
                        )
                        .refreshRequest(
                            AuthProviderCreateRequest.Oauth2.RefreshRequest.builder()
                                .endpoint("endpoint")
                                .authHeaderValueFormat("auth_header_value_format")
                                .authMethod("auth_method")
                                .method("method")
                                .params(
                                    AuthProviderCreateRequest.Oauth2.RefreshRequest.Params.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .requestContentType(
                                    AuthProviderCreateRequest.Oauth2.RefreshRequest
                                        .RequestContentType
                                        .APPLICATION_X_WWW_FORM_URLENCODED
                                )
                                .responseContentType(
                                    AuthProviderCreateRequest.Oauth2.RefreshRequest
                                        .ResponseContentType
                                        .APPLICATION_X_WWW_FORM_URLENCODED
                                )
                                .responseMap(
                                    AuthProviderCreateRequest.Oauth2.RefreshRequest.ResponseMap
                                        .builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .build()
                        )
                        .scopeDelimiter(AuthProviderCreateRequest.Oauth2.ScopeDelimiter.Unknown0)
                        .tokenIntrospectionRequest(
                            AuthProviderCreateRequest.Oauth2.TokenIntrospectionRequest.builder()
                                .endpoint("endpoint")
                                .triggers(
                                    AuthProviderCreateRequest.Oauth2.TokenIntrospectionRequest
                                        .Triggers
                                        .builder()
                                        .onTokenGrant(true)
                                        .onTokenRefresh(true)
                                        .build()
                                )
                                .authHeaderValueFormat("auth_header_value_format")
                                .authMethod("auth_method")
                                .method("method")
                                .params(
                                    AuthProviderCreateRequest.Oauth2.TokenIntrospectionRequest
                                        .Params
                                        .builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .requestContentType(
                                    AuthProviderCreateRequest.Oauth2.TokenIntrospectionRequest
                                        .RequestContentType
                                        .APPLICATION_X_WWW_FORM_URLENCODED
                                )
                                .responseContentType(
                                    AuthProviderCreateRequest.Oauth2.TokenIntrospectionRequest
                                        .ResponseContentType
                                        .APPLICATION_X_WWW_FORM_URLENCODED
                                )
                                .responseMap(
                                    AuthProviderCreateRequest.Oauth2.TokenIntrospectionRequest
                                        .ResponseMap
                                        .builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .build()
                        )
                        .tokenRequest(
                            AuthProviderCreateRequest.Oauth2.TokenRequest.builder()
                                .endpoint("endpoint")
                                .authHeaderValueFormat("auth_header_value_format")
                                .authMethod("auth_method")
                                .method("method")
                                .params(
                                    AuthProviderCreateRequest.Oauth2.TokenRequest.Params.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .requestContentType(
                                    AuthProviderCreateRequest.Oauth2.TokenRequest.RequestContentType
                                        .APPLICATION_X_WWW_FORM_URLENCODED
                                )
                                .responseContentType(
                                    AuthProviderCreateRequest.Oauth2.TokenRequest
                                        .ResponseContentType
                                        .APPLICATION_X_WWW_FORM_URLENCODED
                                )
                                .responseMap(
                                    AuthProviderCreateRequest.Oauth2.TokenRequest.ResponseMap
                                        .builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .build()
                        )
                        .userInfoRequest(
                            AuthProviderCreateRequest.Oauth2.UserInfoRequest.builder()
                                .endpoint("endpoint")
                                .triggers(
                                    AuthProviderCreateRequest.Oauth2.UserInfoRequest.Triggers
                                        .builder()
                                        .onTokenGrant(true)
                                        .onTokenRefresh(true)
                                        .build()
                                )
                                .authHeaderValueFormat("auth_header_value_format")
                                .authMethod("auth_method")
                                .method("method")
                                .params(
                                    AuthProviderCreateRequest.Oauth2.UserInfoRequest.Params
                                        .builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .requestContentType(
                                    AuthProviderCreateRequest.Oauth2.UserInfoRequest
                                        .RequestContentType
                                        .APPLICATION_X_WWW_FORM_URLENCODED
                                )
                                .responseContentType(
                                    AuthProviderCreateRequest.Oauth2.UserInfoRequest
                                        .ResponseContentType
                                        .APPLICATION_X_WWW_FORM_URLENCODED
                                )
                                .responseMap(
                                    AuthProviderCreateRequest.Oauth2.UserInfoRequest.ResponseMap
                                        .builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .providerId("provider_id")
                .status("status")
                .type("type")
                .build()

        val roundtrippedAuthProviderCreateRequest =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(authProviderCreateRequest),
                jacksonTypeRef<AuthProviderCreateRequest>(),
            )

        assertThat(roundtrippedAuthProviderCreateRequest).isEqualTo(authProviderCreateRequest)
    }
}
