// File generated from our OpenAPI spec by Stainless.

package org.arcadeai.api.models

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class ToolDefinitionTest {

    @Test
    fun createToolDefinition() {
        val toolDefinition =
            ToolDefinition.builder()
                .input(
                    ToolDefinition.Input.builder()
                        .addParameter(
                            ToolDefinition.Input.Parameter.builder()
                                .name("name")
                                .valueSchema(
                                    ValueSchema.builder()
                                        .valType("val_type")
                                        .addEnum("string")
                                        .innerValType("inner_val_type")
                                        .build()
                                )
                                .description("description")
                                .inferrable(true)
                                .required(true)
                                .build()
                        )
                        .build()
                )
                .name("name")
                .toolkit(
                    ToolDefinition.Toolkit.builder()
                        .name("name")
                        .description("description")
                        .version("version")
                        .build()
                )
                .description("description")
                .fullyQualifiedName("fully_qualified_name")
                .output(
                    ToolDefinition.Output.builder()
                        .addAvailableMode("string")
                        .description("description")
                        .valueSchema(
                            ValueSchema.builder()
                                .valType("val_type")
                                .addEnum("string")
                                .innerValType("inner_val_type")
                                .build()
                        )
                        .build()
                )
                .requirements(
                    ToolDefinition.Requirements.builder()
                        .authorization(
                            ToolDefinition.Requirements.Authorization.builder()
                                .id("id")
                                .oauth2(
                                    ToolDefinition.Requirements.Authorization.Oauth2.builder()
                                        .addScope("string")
                                        .build()
                                )
                                .providerId("provider_id")
                                .providerType("provider_type")
                                .build()
                        )
                        .build()
                )
                .build()
        assertThat(toolDefinition).isNotNull
        assertThat(toolDefinition.input())
            .isEqualTo(
                ToolDefinition.Input.builder()
                    .addParameter(
                        ToolDefinition.Input.Parameter.builder()
                            .name("name")
                            .valueSchema(
                                ValueSchema.builder()
                                    .valType("val_type")
                                    .addEnum("string")
                                    .innerValType("inner_val_type")
                                    .build()
                            )
                            .description("description")
                            .inferrable(true)
                            .required(true)
                            .build()
                    )
                    .build()
            )
        assertThat(toolDefinition.name()).isEqualTo("name")
        assertThat(toolDefinition.toolkit())
            .isEqualTo(
                ToolDefinition.Toolkit.builder()
                    .name("name")
                    .description("description")
                    .version("version")
                    .build()
            )
        assertThat(toolDefinition.description()).contains("description")
        assertThat(toolDefinition.fullyQualifiedName()).contains("fully_qualified_name")
        assertThat(toolDefinition.output())
            .contains(
                ToolDefinition.Output.builder()
                    .addAvailableMode("string")
                    .description("description")
                    .valueSchema(
                        ValueSchema.builder()
                            .valType("val_type")
                            .addEnum("string")
                            .innerValType("inner_val_type")
                            .build()
                    )
                    .build()
            )
        assertThat(toolDefinition.requirements())
            .contains(
                ToolDefinition.Requirements.builder()
                    .authorization(
                        ToolDefinition.Requirements.Authorization.builder()
                            .id("id")
                            .oauth2(
                                ToolDefinition.Requirements.Authorization.Oauth2.builder()
                                    .addScope("string")
                                    .build()
                            )
                            .providerId("provider_id")
                            .providerType("provider_type")
                            .build()
                    )
                    .build()
            )
    }
}
