// File generated from our OpenAPI spec by Stainless.

package dev.arcade.models.tools

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import dev.arcade.core.JsonValue
import dev.arcade.core.jsonMapper
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class ToolListPageResponseTest {

    @Test
    fun create() {
        val toolListPageResponse =
            ToolListPageResponse.builder()
                .addItem(
                    ToolDefinition.builder()
                        .fullyQualifiedName("fully_qualified_name")
                        .input(
                            ToolDefinition.Input.builder()
                                .addParameter(
                                    ToolDefinition.Input.Parameter.builder()
                                        .name("name")
                                        .valueSchema(
                                            ValueSchema.builder()
                                                .valType("val_type")
                                                .description("description")
                                                .addEnum("string")
                                                .innerProperties(
                                                    ValueSchema.InnerProperties.builder().build()
                                                )
                                                .addInnerRequiredKey("string")
                                                .innerValType("inner_val_type")
                                                .nullable(true)
                                                .properties(
                                                    ValueSchema.Properties.builder().build()
                                                )
                                                .addRequiredKey("string")
                                                .build()
                                        )
                                        .description("description")
                                        .inferrable(true)
                                        .required(true)
                                        .build()
                                )
                                .build()
                        )
                        .name("name")
                        .qualifiedName("qualified_name")
                        .toolkit(
                            ToolDefinition.Toolkit.builder()
                                .name("name")
                                .description("description")
                                .version("version")
                                .build()
                        )
                        .description("description")
                        .formattedSchema(
                            ToolDefinition.FormattedSchema.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .metadata(
                            ToolDefinition.Metadata.builder()
                                .behavior(
                                    ToolDefinition.Metadata.Behavior.builder()
                                        .destructive(true)
                                        .idempotent(true)
                                        .openWorld(true)
                                        .addOperation("string")
                                        .readOnly(true)
                                        .build()
                                )
                                .classification(
                                    ToolDefinition.Metadata.Classification.builder()
                                        .addServiceDomain("string")
                                        .build()
                                )
                                .extras(
                                    ToolDefinition.Metadata.Extras.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                                        .build()
                                )
                                .build()
                        )
                        .output(
                            ToolDefinition.Output.builder()
                                .addAvailableMode("string")
                                .description("description")
                                .valueSchema(
                                    ValueSchema.builder()
                                        .valType("val_type")
                                        .description("description")
                                        .addEnum("string")
                                        .innerProperties(
                                            ValueSchema.InnerProperties.builder().build()
                                        )
                                        .addInnerRequiredKey("string")
                                        .innerValType("inner_val_type")
                                        .nullable(true)
                                        .properties(ValueSchema.Properties.builder().build())
                                        .addRequiredKey("string")
                                        .build()
                                )
                                .build()
                        )
                        .requirements(
                            ToolDefinition.Requirements.builder()
                                .authorization(
                                    ToolDefinition.Requirements.Authorization.builder()
                                        .id("id")
                                        .oauth2(
                                            ToolDefinition.Requirements.Authorization.Oauth2
                                                .builder()
                                                .addScope("string")
                                                .build()
                                        )
                                        .providerId("provider_id")
                                        .providerType("provider_type")
                                        .status(
                                            ToolDefinition.Requirements.Authorization.Status.ACTIVE
                                        )
                                        .statusReason("status_reason")
                                        .tokenStatus(
                                            ToolDefinition.Requirements.Authorization.TokenStatus
                                                .NOT_STARTED
                                        )
                                        .build()
                                )
                                .met(true)
                                .addSecret(
                                    ToolDefinition.Requirements.Secret.builder()
                                        .key("key")
                                        .met(true)
                                        .statusReason("status_reason")
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .limit(0L)
                .offset(0L)
                .pageCount(0L)
                .totalCount(0L)
                .build()

        assertThat(toolListPageResponse.items().getOrNull())
            .containsExactly(
                ToolDefinition.builder()
                    .fullyQualifiedName("fully_qualified_name")
                    .input(
                        ToolDefinition.Input.builder()
                            .addParameter(
                                ToolDefinition.Input.Parameter.builder()
                                    .name("name")
                                    .valueSchema(
                                        ValueSchema.builder()
                                            .valType("val_type")
                                            .description("description")
                                            .addEnum("string")
                                            .innerProperties(
                                                ValueSchema.InnerProperties.builder().build()
                                            )
                                            .addInnerRequiredKey("string")
                                            .innerValType("inner_val_type")
                                            .nullable(true)
                                            .properties(ValueSchema.Properties.builder().build())
                                            .addRequiredKey("string")
                                            .build()
                                    )
                                    .description("description")
                                    .inferrable(true)
                                    .required(true)
                                    .build()
                            )
                            .build()
                    )
                    .name("name")
                    .qualifiedName("qualified_name")
                    .toolkit(
                        ToolDefinition.Toolkit.builder()
                            .name("name")
                            .description("description")
                            .version("version")
                            .build()
                    )
                    .description("description")
                    .formattedSchema(
                        ToolDefinition.FormattedSchema.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .metadata(
                        ToolDefinition.Metadata.builder()
                            .behavior(
                                ToolDefinition.Metadata.Behavior.builder()
                                    .destructive(true)
                                    .idempotent(true)
                                    .openWorld(true)
                                    .addOperation("string")
                                    .readOnly(true)
                                    .build()
                            )
                            .classification(
                                ToolDefinition.Metadata.Classification.builder()
                                    .addServiceDomain("string")
                                    .build()
                            )
                            .extras(
                                ToolDefinition.Metadata.Extras.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                                    .build()
                            )
                            .build()
                    )
                    .output(
                        ToolDefinition.Output.builder()
                            .addAvailableMode("string")
                            .description("description")
                            .valueSchema(
                                ValueSchema.builder()
                                    .valType("val_type")
                                    .description("description")
                                    .addEnum("string")
                                    .innerProperties(ValueSchema.InnerProperties.builder().build())
                                    .addInnerRequiredKey("string")
                                    .innerValType("inner_val_type")
                                    .nullable(true)
                                    .properties(ValueSchema.Properties.builder().build())
                                    .addRequiredKey("string")
                                    .build()
                            )
                            .build()
                    )
                    .requirements(
                        ToolDefinition.Requirements.builder()
                            .authorization(
                                ToolDefinition.Requirements.Authorization.builder()
                                    .id("id")
                                    .oauth2(
                                        ToolDefinition.Requirements.Authorization.Oauth2.builder()
                                            .addScope("string")
                                            .build()
                                    )
                                    .providerId("provider_id")
                                    .providerType("provider_type")
                                    .status(ToolDefinition.Requirements.Authorization.Status.ACTIVE)
                                    .statusReason("status_reason")
                                    .tokenStatus(
                                        ToolDefinition.Requirements.Authorization.TokenStatus
                                            .NOT_STARTED
                                    )
                                    .build()
                            )
                            .met(true)
                            .addSecret(
                                ToolDefinition.Requirements.Secret.builder()
                                    .key("key")
                                    .met(true)
                                    .statusReason("status_reason")
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(toolListPageResponse.limit()).contains(0L)
        assertThat(toolListPageResponse.offset()).contains(0L)
        assertThat(toolListPageResponse.pageCount()).contains(0L)
        assertThat(toolListPageResponse.totalCount()).contains(0L)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val toolListPageResponse =
            ToolListPageResponse.builder()
                .addItem(
                    ToolDefinition.builder()
                        .fullyQualifiedName("fully_qualified_name")
                        .input(
                            ToolDefinition.Input.builder()
                                .addParameter(
                                    ToolDefinition.Input.Parameter.builder()
                                        .name("name")
                                        .valueSchema(
                                            ValueSchema.builder()
                                                .valType("val_type")
                                                .description("description")
                                                .addEnum("string")
                                                .innerProperties(
                                                    ValueSchema.InnerProperties.builder().build()
                                                )
                                                .addInnerRequiredKey("string")
                                                .innerValType("inner_val_type")
                                                .nullable(true)
                                                .properties(
                                                    ValueSchema.Properties.builder().build()
                                                )
                                                .addRequiredKey("string")
                                                .build()
                                        )
                                        .description("description")
                                        .inferrable(true)
                                        .required(true)
                                        .build()
                                )
                                .build()
                        )
                        .name("name")
                        .qualifiedName("qualified_name")
                        .toolkit(
                            ToolDefinition.Toolkit.builder()
                                .name("name")
                                .description("description")
                                .version("version")
                                .build()
                        )
                        .description("description")
                        .formattedSchema(
                            ToolDefinition.FormattedSchema.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .metadata(
                            ToolDefinition.Metadata.builder()
                                .behavior(
                                    ToolDefinition.Metadata.Behavior.builder()
                                        .destructive(true)
                                        .idempotent(true)
                                        .openWorld(true)
                                        .addOperation("string")
                                        .readOnly(true)
                                        .build()
                                )
                                .classification(
                                    ToolDefinition.Metadata.Classification.builder()
                                        .addServiceDomain("string")
                                        .build()
                                )
                                .extras(
                                    ToolDefinition.Metadata.Extras.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                                        .build()
                                )
                                .build()
                        )
                        .output(
                            ToolDefinition.Output.builder()
                                .addAvailableMode("string")
                                .description("description")
                                .valueSchema(
                                    ValueSchema.builder()
                                        .valType("val_type")
                                        .description("description")
                                        .addEnum("string")
                                        .innerProperties(
                                            ValueSchema.InnerProperties.builder().build()
                                        )
                                        .addInnerRequiredKey("string")
                                        .innerValType("inner_val_type")
                                        .nullable(true)
                                        .properties(ValueSchema.Properties.builder().build())
                                        .addRequiredKey("string")
                                        .build()
                                )
                                .build()
                        )
                        .requirements(
                            ToolDefinition.Requirements.builder()
                                .authorization(
                                    ToolDefinition.Requirements.Authorization.builder()
                                        .id("id")
                                        .oauth2(
                                            ToolDefinition.Requirements.Authorization.Oauth2
                                                .builder()
                                                .addScope("string")
                                                .build()
                                        )
                                        .providerId("provider_id")
                                        .providerType("provider_type")
                                        .status(
                                            ToolDefinition.Requirements.Authorization.Status.ACTIVE
                                        )
                                        .statusReason("status_reason")
                                        .tokenStatus(
                                            ToolDefinition.Requirements.Authorization.TokenStatus
                                                .NOT_STARTED
                                        )
                                        .build()
                                )
                                .met(true)
                                .addSecret(
                                    ToolDefinition.Requirements.Secret.builder()
                                        .key("key")
                                        .met(true)
                                        .statusReason("status_reason")
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .limit(0L)
                .offset(0L)
                .pageCount(0L)
                .totalCount(0L)
                .build()

        val roundtrippedToolListPageResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(toolListPageResponse),
                jacksonTypeRef<ToolListPageResponse>(),
            )

        assertThat(roundtrippedToolListPageResponse).isEqualTo(toolListPageResponse)
    }
}
